#!/usr/bin/python3

import sys, subprocess

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def main(argv):
    print(f"- {bcolors.OKBLUE}Install python3-pip{bcolors.ENDC}")
    process = subprocess.Popen(['sudo', "apt-get", "install", "-y", "--fix-missing" "python3-pip"], stdout=subprocess.PIPE)
    subProcessOutput, subProcessError = process.communicate()

    print(f"- {bcolors.OKBLUE}Install gitPython{bcolors.ENDC}")
    process = subprocess.Popen(['pip3', "install", "gitpython"], stdout=subprocess.PIPE)
    subProcessOutput, subProcessError = process.communicate()

    print(f"- {bcolors.OKBLUE}Chmod +x to script{bcolors.ENDC}")
    process = subprocess.Popen(['chmod', "+x", "multidocker"], stdout=subprocess.PIPE)
    subProcessOutput, subProcessError = process.communicate()

    print(f"- {bcolors.OKBLUE}Install script to bin{bcolors.ENDC}")
    process = subprocess.Popen(['sudo', "cp", "multidocker", "/usr/local/bin"], stdout=subprocess.PIPE)
    subProcessOutput, subProcessError = process.communicate()

main = main(sys.argv)
